config:
  MD013: false
  MD024:
    siblings_only: true
  MD033:
    allowed_elements:
      - details
      - summary
      - description
  MD036: false
  MD040: false
  MD041: false
  MD060: false

ignores:
  - "**/node_modules"
  - "**/.claude/plans"
